### ISSUE TITLE
使用初始化的裁剪框cropBoxInfo 报错

### ISSUE THREAD

**Issue by nitenzhao** [likaia/js-screen-shot#60]
在使用初始化的裁剪框cropBoxInfo时，如果不拖动裁剪框 直接点确认按钮，就会报下面的异常：
`
screenShotPlugin.common.js:12767 Uncaught DOMException: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source width is 0.
    at saveCanvasToBase64 (http://localhost/ui/accident/app.js:123863:21)
    at getCanvasImgData (http://localhost/ui/accident/app.js:123920:16)
    at toolClickEvent (http://localhost/ui/accident/app.js:124232:18)
    at HTMLDivElement.<anonymous> (http://localhost/ui/accident/app.js:124468:13)
`
如果拖动一下裁剪框，就能正常裁剪

**Comment by likaia** [comment]
已修复，插件更新至1.7.1即可
